import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet"></link>
            <script src="https://kit.fontawesome.com/0821b4c791.js" async></script>
      </head>
      <body className={inter.className} 
      >
        <main className="flex min-h-screen flex-col bg-[#121212]">
            <Navbar/>
              {children}
           <Footer/>
        </main>
      </body>
    </html>
  );
}
